#!/usr/bin/env bash
# Install nginx on your web-01

# Update the package lists for available software packages
apt-get update

# Install the Nginx web server
apt-get install -y nginx

# Create a basic HTML page with "Hello World!"
mkdir -p /nginx/html
echo "Hello World!" > /nginx/html/index.html

# Ensure Nginx is listening on port 80
printf %s "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
