#!/usr/bin/env bash
# Nginx server have a custom 404 page that contains the string Ceci n'est pas une page

#  updates the package lists for available software packages.
apt-get update

# installs the Nginx web server.
apt-get install -y nginx

# Create a basic HTML page with "Hello World!"
mkdir -p /nginx/html
echo "Hello World!" > /nginx/html/index.html

# Ensure Nginx is listening on port 80
printf %s "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Create a basic HTML page with "Ceci n'est pas une page"
mkdir -p /nginx/html
echo "Ceci n'est pas une page" > /nginx/html/404.html

# Create a configuration file for the redirection
echo "server {
    listen      80;
    listen      [::]:80;
    root        /nginx/html;
    index       index.html index.htm;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
      root /nginx/html;
      internal;
    }

}" > /etc/nginx/sites-available/default

# Enable new site configuration
ln -s /etc/nginx/sites-available/redirect /nginx/sites-enabled/

# Test Nginx configuration and reload
nginx -t
service nginx reload
