#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
systemctl start nginx
systemctl status nginx | grep -q "active (running)" && systemctl restart nginx
