#!/usr/bin/env bash
# Bash (init) script that manages manage_my_process

case "$1" in
start)
if [ -f "/var/run/my_process.pid" ]
then
echo "manage_my_process is already running."
else
./manage_my_process &
echo $$ > /var/run/my_process.pid
echo "manage_my_process started"
fi
;;
stop)
if [ -f "/var/run/my_process.pid" ]
then
pid=$(cat "$/var/run/my_process.pid")
kill "$pid"
rm /var/run/my_process.pid
echo "manage_my_process stopped"
else
echo "manage_my_process is not running."
fi
;;
restart)
kill "$(pgrep -f ./manage_my_process)"
rm /var/run/my_process.pid
./manage_my_process &
echo $$ > /var/run/my_process.pid
echo "manage_my_process restarted"
;;
*)
echo  "Usage: manage_my_process {start|stop|restart}"
;;
esac
