#!/usr/bin/env bash
# Bash script that displays the PID, along with the process name
# of processes whose name contain the word bash

for dir in /proc/[0-9]*/
do
pid=$(basename "$dir")
if [ -f "/proc/$pid/status" ] && [ -r "/proc/$pid/status" ]
then
process_name=$(awk '/Name/ {print $2}' "/proc/$pid/status")
if [[ "$process_name" == *"bash"* ]] && [ "$pid" != "$$" ]
then
echo "$pid $process_name"
fi
fi
done
