#!/usr/bin/env bash
# Bash script that displays the PID, along with the process name
# of processes whose name contain the word bash

for dir in /proc/[0-9]*/
do
pid=$(basename "$dir")
if [ -f "$dir/cmdline" ] && [ -r "$dir/cmdline" ]
then
read -r cmdline < "$dir/cmdline"
if [[ "$cmdline" == *"bash"* ]] && [ "$pid" != "$$" ]
then
echo "$pid $cmdline"
fi
fi
done
