#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

if [[ $EUID -ne 0 ]]
then
echo "Please use sudo."
exit 1
fi

LOCALHOST_IP="127.0.0.2"
FACEBOOK_IP="8.8.8.8"

cp /etc/hosts ~/hosts.new

sed -i "s/^127\.0\.0\.1\slocalhost$/127.0.0.1 localhost\n$LOCALHOST_IP localhost/" ~/hosts.new
echo "$FACEBOOK_IP facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
