#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

LOCALHOST_IP="127.0.0.2"
FACEBOOK_IP="8.8.8.8"

cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.1.*/$LOCALHOST_IP localhost/g' ~/hosts.new
echo "$FACEBOOK_IP facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
